apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-devops-nodejs
  namespace: devops
  name: demo-devops-nodejs
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: demo-devops-nodejs
  type: ClusterIP
