on:
  push:
jobs:
  test_app:
    name: Testing Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - name: Test NodeJS app
        run: npm run test