on:
  push:
jobs:
  test_app:
    name: Testing Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Test NodeJS app
        run: npm run test

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build Node App
    needs: [test_app, sonarcloud]
    runs-on: ubuntu-latest
    steps:
      - run: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Define image tag from commit sha
        run: |
          IMAGE_TAG=`echo ${GITHUB_SHA} | cut -b -10`
          echo IMAGE_TAG=$IMAGE_TAG >> "$GITHUB_ENV"
          IMAGE_REPO=`echo ${GITHUB_REPOSITORY} | cut -d '/' -f 2`
          echo IMAGE_REPO=$IMAGE_REPO >> "$GITHUB_ENV"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: rentgonz/${{ env.IMAGE_TAG }}:${{ env.IMAGE_TAG }}
